on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Unit Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dockerfile action
        uses: ./ # Uses an action in the root directory
      - uses: actions/upload-artifact@main
        with:
          name: artifacts
          path: .
 
